title: Abhirup Guhathakurta
logo: https://github.com/Green2410/portfolio/blob/main/_assets/Abhirup_Guhathakurta_Image.jpg?raw=true
show_downloads: false
theme: jekyll-theme-minimal

github_username: Green2410
linkedin_username: Abhirup Guhathakurta
email: abhirupguhathakurta5@gnail.com

plugins:
  - jekyll-seo-tag
