title: Abhirup Guhathakurta
show_downloads: false
theme: jekyll-theme-minimal

github_username: Green2410
linkedin_username: your-linkedin-username
email: your.email@example.com

plugins:
  - jekyll-seo-tag
